# Generated by Django 2.2.10 on 2021-10-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poll_Answer',
            new_name='PollAnswer',
        ),
        migrations.RenameModel(
            old_name='Poll_Question',
            new_name='PollQuestion',
        ),
    ]
